export const ACCESS_COOKIE = 'fieldops_access';
export const REFRESH_COOKIE = 'fieldops_refresh';
export const CSRF_HEADER = 'x-fieldops-requested-with';
export const CSRF_HEADER_VALUE = 'web';
export const DEFAULT_PLAN_CODE = 'starter';
export const TRIAL_PLAN_CODE = 'professional';
export const BUSINESS_PLAN_CODE = 'business';
export const TRIAL_DAYS = 14;
export const TRIAL_GRACE_DAYS = 3;
export const TRIAL_ENDING_SOON_DAYS = 3;
export const PAID_GRACE_DAYS = 7;
export const ANNUAL_PERIOD_YEARS = 1;
export const RENEWAL_REMINDER_DAYS = [30, 14, 7, 1] as const;
export const DEFAULT_SALES_EMAIL = 'sales@fieldops.local';
export const DEFAULT_SUPPORT_EMAIL = 'support@fieldops.local';
export const DEFAULT_SECURITY_EMAIL = 'security@fieldops.local';
export const TERMS_VERSION = '2026-09-23';
export const PRIVACY_VERSION = '2026-09-23';
export const BILLING_POLICY_VERSION = '2026-09-23';
export const LEGAL_EFFECTIVE_DATE = '2026-09-23';
export const INVOICE_NUMBER_PREFIX = 'FC';
export const INVOICE_NUMBER_PAD = 6;
export const INVOICE_DUE_DAYS = 14;

export const AUDIT_INVOICE_CREATED = 'INVOICE_CREATED';
export const AUDIT_INVOICE_ISSUED = 'INVOICE_ISSUED';
export const AUDIT_INVOICE_PAID = 'INVOICE_PAID';
export const AUDIT_INVOICE_VOIDED = 'INVOICE_VOIDED';
export const AUDIT_INVOICE_PAYMENT_NOTICE = 'INVOICE_PAYMENT_NOTICE';
export const AUDIT_INVOICE_OVERDUE = 'INVOICE_OVERDUE';
export const AUDIT_BILLING_SETTINGS_UPDATED = 'BILLING_SETTINGS_UPDATED';

export const AUDIT_TRIAL_STARTED = 'TRIAL_STARTED';
export const AUDIT_TRIAL_EXTENDED = 'TRIAL_EXTENDED';
export const AUDIT_ACTIVATION_REQUESTED = 'ACTIVATION_REQUESTED';
export const AUDIT_RENEWAL_REQUESTED = 'RENEWAL_REQUESTED';
export const AUDIT_PLAN_CHANGED = 'PLAN_CHANGED';
export const AUDIT_PLAN_CHANGE_REQUESTED = 'PLAN_CHANGE_REQUESTED';
export const AUDIT_PLAN_LIMIT_BLOCKED = 'PLAN_LIMIT_BLOCKED';
export const AUDIT_ORGANIZATION_ACTIVATED = 'ORGANIZATION_ACTIVATED';
export const AUDIT_ORGANIZATION_SUSPENDED = 'ORGANIZATION_SUSPENDED';
export const AUDIT_ORGANIZATION_REACTIVATED = 'ORGANIZATION_REACTIVATED';
export const AUDIT_ORGANIZATION_CANCELLED = 'ORGANIZATION_CANCELLED';
export const AUDIT_ACTIVATION_REQUEST_UPDATED = 'ACTIVATION_REQUEST_UPDATED';
/** @deprecated Prefer AUDIT_ORGANIZATION_ACTIVATED — kept as alias for older call sites. */
export const AUDIT_SUBSCRIPTION_ACTIVATED = AUDIT_ORGANIZATION_ACTIVATED;
export const AUDIT_SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED';
export const AUDIT_SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED';
export const AUDIT_SUBSCRIPTION_SUSPENDED = AUDIT_ORGANIZATION_SUSPENDED;
export const AUDIT_SUBSCRIPTION_REACTIVATED = AUDIT_ORGANIZATION_REACTIVATED;
export const AUDIT_SUBSCRIPTION_CANCELLED = AUDIT_ORGANIZATION_CANCELLED;

export const NOTIFICATION_TRIAL_ENDING = 'TRIAL_ENDING_SOON';
export const NOTIFICATION_TRIAL_EXPIRING = 'TRIAL_EXPIRING';
export const NOTIFICATION_TRIAL_GRACE = 'TRIAL_GRACE';
export const NOTIFICATION_TRIAL_EXPIRED = 'TRIAL_EXPIRED';
export const NOTIFICATION_ACTIVATION_REQUESTED = 'ACTIVATION_REQUESTED';
export const NOTIFICATION_ACTIVATION_ACK = 'ACTIVATION_REQUEST_ACK';
export const NOTIFICATION_PLAN_CHANGE_REQUESTED = 'PLAN_CHANGE_REQUESTED';
export const NOTIFICATION_PLAN_CHANGE_ACK = 'PLAN_CHANGE_REQUEST_ACK';
export const NOTIFICATION_SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED';
export const NOTIFICATION_RENEWAL_PREFIX = 'RENEWAL_';
export const NOTIFICATION_SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED';
export const NOTIFICATION_RENEWAL_REQUESTED = 'RENEWAL_REQUESTED';
export const NOTIFICATION_SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED';
export const NOTIFICATION_WORKSPACE_READ_ONLY = 'WORKSPACE_READ_ONLY';
export const NOTIFICATION_INVITATION = 'INVITATION';
export const NOTIFICATION_JOB_ASSIGNED = 'JOB_ASSIGNED';
export const NOTIFICATION_JOB_RESCHEDULED = 'JOB_RESCHEDULED';
export const AUDIT_CLIENT_CREATED = 'CLIENT_CREATED';
export const AUDIT_CLIENT_UPDATED = 'CLIENT_UPDATED';
export const AUDIT_CLIENT_DEACTIVATED = 'CLIENT_DEACTIVATED';
export const AUDIT_SITE_CREATED = 'SITE_CREATED';
export const AUDIT_SITE_UPDATED = 'SITE_UPDATED';
export const AUDIT_SITE_DEACTIVATED = 'SITE_DEACTIVATED';
export const AUDIT_TEAM_CREATED = 'TEAM_CREATED';
export const AUDIT_TEAM_UPDATED = 'TEAM_UPDATED';
export const AUDIT_TEAM_MEMBER_ADDED = 'TEAM_MEMBER_ADDED';
export const AUDIT_TEAM_MEMBER_REMOVED = 'TEAM_MEMBER_REMOVED';
export const AUDIT_TEAM_SUPERVISOR_CHANGED = 'TEAM_SUPERVISOR_CHANGED';
export const AUDIT_SKILL_ASSIGNED = 'SKILL_ASSIGNED';
export const AUDIT_CERTIFICATION_ADDED = 'CERTIFICATION_ADDED';
export const AUDIT_CERTIFICATION_UPDATED = 'CERTIFICATION_UPDATED';
export const AUDIT_JOB_CREATED = 'JOB_CREATED';
export const AUDIT_JOB_UPDATED = 'JOB_UPDATED';
export const AUDIT_JOB_SCHEDULED = 'JOB_SCHEDULED';
export const AUDIT_JOB_RESCHEDULED = 'JOB_RESCHEDULED';
export const AUDIT_JOB_ASSIGNED = 'JOB_ASSIGNED';
export const AUDIT_JOB_REASSIGNED = 'JOB_REASSIGNED';
export const AUDIT_JOB_DISPATCHED = 'JOB_DISPATCHED';
export const AUDIT_JOB_STARTED = 'JOB_STARTED';
export const AUDIT_JOB_SUBMITTED = 'JOB_SUBMITTED';
export const AUDIT_JOB_COMPLETED = 'JOB_COMPLETED';
export const AUDIT_JOB_APPROVED = 'JOB_APPROVED';
export const AUDIT_JOB_RETURNED = 'JOB_RETURNED';
export const AUDIT_JOB_CANCELLED = 'JOB_CANCELLED';
export const AUDIT_CLOCK_IN = 'CLOCK_IN';
export const AUDIT_CLOCK_OUT = 'CLOCK_OUT';
export const AUDIT_TIME_ENTRY_CREATED = 'TIME_ENTRY_CREATED';
export const AUDIT_TIME_ENTRY_UPDATED = 'TIME_ENTRY_UPDATED';
export const AUDIT_TIME_ENTRY_SUBMITTED = 'TIME_ENTRY_SUBMITTED';
export const AUDIT_TIME_ENTRY_APPROVED = 'TIME_ENTRY_APPROVED';
export const AUDIT_TIME_ENTRY_RETURNED = 'TIME_ENTRY_RETURNED';
export const AUDIT_TIME_ENTRY_REJECTED = 'TIME_ENTRY_REJECTED';
export const AUDIT_TIME_APPROVED = 'TIME_APPROVED';
export const AUDIT_TIME_RETURNED = 'TIME_RETURNED';
export const MANUAL_TIME_MIN_MINUTES = 15;
export const MANUAL_TIME_DESCRIPTION_MIN = 8;
export const DEFAULT_DAILY_HOURS_LIMIT = 8;
export const DEFAULT_WEEKLY_HOURS_LIMIT = 40;
export const TIMESHEET_MAX_FUTURE_WEEKS = 1;
export const CLOCK_OUT_IDEMPOTENT_MS = 120_000;
export const AUDIT_OVERTIME_REQUESTED = 'OVERTIME_REQUESTED';
export const AUDIT_OVERTIME_APPROVED = 'OVERTIME_APPROVED';
export const AUDIT_OVERTIME_REJECTED = 'OVERTIME_REJECTED';
export const AUDIT_OVERTIME_CANCELLED = 'OVERTIME_CANCELLED';
export const NOTIFICATION_OVERTIME_REQUESTED = 'OVERTIME_REQUESTED';
export const NOTIFICATION_OVERTIME_APPROVED = 'OVERTIME_APPROVED';
export const NOTIFICATION_OVERTIME_REJECTED = 'OVERTIME_REJECTED';
export const NOTIFICATION_OVERTIME_CANCELLED = 'OVERTIME_CANCELLED';
export const NOTIFICATION_JOB_APPROVAL_REQUESTED = 'JOB_APPROVAL_REQUESTED';
export const NOTIFICATION_JOB_APPROVED = 'JOB_APPROVED';
export const NOTIFICATION_JOB_RETURNED = 'JOB_RETURNED';
export const NOTIFICATION_TIME_APPROVAL_REQUESTED = 'TIMESHEET_SUBMITTED';
export const NOTIFICATION_TIME_APPROVED = 'TIMESHEET_APPROVED';
export const NOTIFICATION_TIME_RETURNED = 'TIMESHEET_RETURNED';
export const NOTIFICATION_TIMESHEET_SUBMITTED = NOTIFICATION_TIME_APPROVAL_REQUESTED;
export const NOTIFICATION_TIMESHEET_APPROVED = NOTIFICATION_TIME_APPROVED;
export const NOTIFICATION_TIMESHEET_RETURNED = NOTIFICATION_TIME_RETURNED;
export const AUDIT_JOB_WORK_LOG = 'WORK_LOG_ADDED';
export const AUDIT_JOB_WORK_LOG_UPDATED = 'WORK_LOG_UPDATED';
export const AUDIT_JOB_MATERIAL = 'MATERIAL_ADDED';
export const AUDIT_JOB_MATERIAL_UPDATED = 'MATERIAL_UPDATED';
export const AUDIT_JOB_MATERIAL_REMOVED = 'MATERIAL_REMOVED';
export const AUDIT_SAFETY_CONTROL_CONFIRMED = 'SAFETY_CONTROL_CONFIRMED';
export const AUDIT_COMPLETION_SUMMARY_UPDATED = 'COMPLETION_SUMMARY_UPDATED';
export const AUDIT_JOB_PHOTO = 'JOB_PHOTO';
export const AUDIT_JOB_SIGNATURE = 'JOB_SIGNATURE';
export const AUDIT_FILE_UPLOADED = 'FILE_UPLOADED';
export const AUDIT_FILE_DELETED = 'FILE_DELETED';
export const AUDIT_CLIENT_SIGNATURE_CAPTURED = 'CLIENT_SIGNATURE_CAPTURED';
export const AUDIT_CLIENT_SIGNOFF_UPDATED = 'CLIENT_SIGNOFF_UPDATED';
export const SAFETY_CONTROL_CODES = [
  'RISK_ASSESSMENT',
  'PERMIT',
  'LOTO',
] as const;
export type SafetyControlCode = (typeof SAFETY_CONTROL_CODES)[number];
export const MATERIAL_UNITS = [
  'ea',
  'pcs',
  'set',
  'm',
  'ft',
  'kg',
  'L',
  'box',
  'other',
] as const;
export type MaterialUnit = (typeof MATERIAL_UNITS)[number];
export const WORK_PERFORMED_MIN_LENGTH = 8;
export const PHOTO_MAX_BYTES = 8 * 1024 * 1024;
export const DOCUMENT_MAX_BYTES = 10 * 1024 * 1024;
/** Default GET presign TTL when env is unset (seconds). Prefer S3_PRESIGNED_GET_EXPIRY_SECONDS. */
export const FILE_PRESIGN_TTL_SECONDS = 300;
export const PHOTO_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
] as const;
export const SIGNATURE_MIME_TYPES = ['image/png', 'image/jpeg'] as const;
export const DOCUMENT_MIME_TYPES = [
  'application/pdf',
  'image/jpeg',
  'image/png',
] as const;
export const JOB_TYPES = [
  'SERVICE_CALL',
  'INSTALLATION',
  'MAINTENANCE',
  'INSPECTION',
  'EMERGENCY',
  'OTHER',
] as const;
export type JobTypeCode = (typeof JOB_TYPES)[number];
export const JOB_NUMBER_PAD = 6;
export const CERTIFICATION_EXPIRING_SOON_DAYS = 30;
export const DEFAULT_JOB_WINDOW_MINUTES = 120;
export { DEFAULT_GPS_REVIEW_DISTANCE_METERS } from './geo.js';
export const BCRYPT_ROUNDS = 12;
export const EMAIL_VERIFICATION_TTL_HOURS = 24;
export const INVITATION_TTL_DAYS = 7;
export const WORK_WEEK_DAYS = [
  'MON',
  'TUE',
  'WED',
  'THU',
  'FRI',
  'SAT',
  'SUN',
] as const;
export type WorkWeekDay = (typeof WORK_WEEK_DAYS)[number];
export const DEFAULT_WORKING_WEEK: WorkWeekDay[] = [
  'MON',
  'TUE',
  'WED',
  'THU',
  'FRI',
];
